### ISSUE TITLE
TypeMapper.js error after updating to 2.24.1

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#60]
```
yarn run v1.6.0
$ gatsby develop
/Users/Kallirroi/Documents/code/shannon/exploring/wordpress-tutorial-site/node_modules/gatsby-recipes/node_modules/graphql-compose/lib/TypeMapper.js:294
        throw new Error(`${typeName}.${fieldName} provided incorrect OutputType: '${(0, _misc.inspect)(composeType)}'`);
        ^

Error: GatsbyPlugin.options provided incorrect OutputType: 'JSONObject'
    at TypeMapper.convertOutputFieldConfig (/Users/Kallirroi/Documents/code/shannon/exploring/wordpress-tutorial-site/node_modules/gatsby-recipes/node_modules/graphql-compose/lib/TypeMapper.js:294:15)
    at resolveOutputConfigAsThunk (/Users/Kallirroi/Documents/code/shannon/exploring/wordpress-tutorial-site/node_modules/gatsby-recipes/node_modules/graphql-compose/lib/utils/configAsThunk.js:19:41)
    at ObjectTypeComposer.getFieldConfig (/Users/Kallirroi/Documents/code/shannon/exploring/wordpress-tutorial-site/node_modules/gatsby-recipes/node_modules/graphql-compose/lib/ObjectTypeComposer.js:300:58)
    at /Users/Kallirroi/Documents/code/shannon/exploring/wo
rdpress-tutorial-site/node_modules/gatsby-recipes/node_modules/graphql-compose/lib/utils/toInputObjectType.js:44:19
    at Array.forEach (<anonymous>)
    at toInputObjectType (/Users/Kallirroi/Documents/code/shannon/exploring/wordpress-tutorial-site/node_modules/gatsby-recipes/node_modules/graphql-compose/lib/utils/toInputObjectType.js:38:14)
    at ObjectTypeComposer.getInputTypeComposer (/Users/Kallirroi/Documents/code/shannon/exploring/wordpress-tutorial-site/node_modules/gatsby-recipes/node_modules/graphql-compose/lib/ObjectTypeComposer.js:600:84)
    at ObjectTypeComposer.getInputType (/Users/Kallirroi/Documents/code/shannon/exploring/wordpress-tutorial-site/node_modules/gatsby-recipes/node_modules/graphql-compose/lib/ObjectTypeComposer.js:586:17)
    at /Users/Kallirroi/Documents/code/shannon/exploring/wordpress-tutorial-site/node_modules/gatsby-recipes/dist/create-types.js:86:71
    at Array.map (<anonymous>)

Debugger listening on ws://127.0.0.1:9229/6aa639d7-7a52-48c2-a048-b3a39d63211d
For help, see: https://nodejs.org/en/docs/inspector
success open and validate gatsby-configs - 0.050s
success load plugins - 1.482s
success onPreInit - 0.043s
success initialize cache - 0.009s
success copy gatsby files - 0.116s
success onPreBootstrap - 0.012s

 ERROR

 gatsby-source-wordpress  Your remote version of WPGraphQL is not within the accepted range (~0.10.3).

	Download v ~0.10.3 at https://github.com/wp-graphql/wp-graphql/releases

	If you're upgrading from an earlier version, read the release notes for each version between your old and new versions to determine which breaking changes you might encounter based on your use of the schema.


Reasons:

- WPGraphQL 0.10.0 introduced a large number of changes that required internal source plugin code changes. A big feature is improved support for WordPress previews and improvements to how Menus are handled. 0.10.3 fixed a private post regression that could cause cold builds to fail. Head to https://github.com/wp-graphql/wp-graphql/releases/tag/v0.10.0 for more information on upgrading.

- WPGatsby 0.4.1 supports WPGraphQL 0.10.0


not finished createSchemaCustomization - 2.492s
error Command failed with exit code 1.
```

Downgrading plugin back to `0.10.3` throws same error, but without exiting.

Possibly having to do with updating Gatsby version to `^2.24.1`, which was done to address the `staticQuery` bug on deploy.

**Comment by Kallirroi** [comment]
https://github.com/gatsbyjs/gatsby/issues/26111

**Comment by Kallirroi** [comment]
btw I don't see this on the build logs on Vercel

**Comment by Kallirroi** [comment]
unassigning since not pressing

**Comment by Kallirroi** [comment]
Closing for now since it only appears during dev
